### ISSUE TITLE
Слетает кодировка;

### ISSUE THREAD

**Issue by sergeybrava** [dyadyal/dl-yandex-metrika#1]
Привет, Дядь Леша.
Поставили твою прекрастную игрульку для ЯндексМетрики на ВП. 
И сразу же у нас подлетала вся кодировка  в админке.

Сейчас, конечно, проверим, моя у нас чего. Но странно.

**Comment by dyadyal** [comment]
Очень интересно, проверял на всех своих сайтах(более 20), все работает хорошо, возможно настройки сервера, по возможности скиньте скриншоты, разберемся!

**Comment by sergeybrava** [comment]
Можно по Тимвьюверу даж ) Или завтречко уже.

**Comment by dyadyal** [comment]
ОК, тогда по почте можно списаться и посмотрим в чем проблема! info@dd-l.name

**Comment by nesutulsa** [comment]
otpravil
